repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff check --fix .
        language: system
        types_or: [python, pyi]

      - id: ruff-format
        name: ruff format
        entry: ruff format .
        language: system
        types_or: [python, pyi]

      - id: mypy
        name: mypy
        entry: mypy src/llm_client
        language: system
        pass_filenames: false
        types_or: [python, pyi]
